# Generated by Django 3.1 on 2020-08-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='tarih',
        ),
    ]
