language: python
python: 3.7

services:
  - docker

install:
  - 'pip install poetry'
  - 'poetry install'

script:
  - poetry run pre-commit run --all-files

before_deploy:
  # Checking out the branch is necessary because Travis operates in a
  # "detached HEAD" state. This breaks git-based inspection of current
  # branch, which is used in the following "version" logic
  - git checkout $TRAVIS_BRANCH
  - ./scripts/build.sh

deploy:
  - provide: s3
    skip_cleanup: true
    bucket: sentera-build-packages
    local-dir: dist
    upload-dir: yield-estimation
    acl: private
    on:
      branch: master
